### ISSUE TITLE
Run automated deployment on CI server

### ISSUE THREAD

**Issue by enriquegh** [mdsauce/schelper#12]
Could run a simple Travis script that runs the tests and then makes a new release on Github.
https://docs.travis-ci.com/user/deployment/releases/

**Comment by mdsauce** [comment]
Started the process with #14. Still have to do the release portion.

**Comment by mdsauce** [comment]
Using git tag and homebrew for releases: https://git-scm.com/book/en/v2/Git-Basics-Tagging.  Non-windows deployment can be added as needed but most package managers can work with the .tar.gz files generated via tagging.
