### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by enriquegh** [mdsauce/schelper#22]
Currently there is no way to see what version of schelper you are using (unless you downloaded it from brew and look there).

It'd be good to add a --version flag that outputs the version number.

**Comment by mdsauce** [comment]
Adding version via -X linker flag during `go build`.  Example here: https://www.atatus.com/blog/golang-auto-build-versioning/

Will use `Version` in the schelper brew file: https://github.com/mdsauce/schelper-brew/blob/master/schelper.rb

**Comment by mdsauce** [comment]
- [ ] Add current version to logs at startup
- [ ] Add --version flag that outputs the current version
- [ ] Add default version 'DEV'

**Comment by mdsauce** [comment]
https://golang.org/cmd/link/ the -X arg is an option during the linking process.  This is used in practice like so: `go build -ldflags "-X github.com/mdsauce/schelper/cmd.CurVersion=1.0.5"`

`schelper --version` will output:
`schelper version < -X argument here >`
